# Generated by Django 3.2.7 on 2021-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetutilizedistrict',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
