# Generated by Django 3.2.7 on 2021-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetutilizedistrict_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsdbudget',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
