# Generated by Django 3.2.7 on 2021-10-23 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('director', 'Director'), ('dho', 'DHO'), ('store_keeper', 'Store keeper'), ('data_entry_operator', 'Data Entry Operator')], default='director', max_length=100)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('office_address', models.TextField(blank=True, max_length=512, null=True)),
                ('city', models.TextField(blank=True, max_length=512, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=13, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=13, null=True)),
                ('picture', models.ImageField(blank=True, max_length=1024, upload_to='images/profile/picture/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
