# Generated by Django 3.2.7 on 2021-11-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211117_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_formula_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
        migrations.CreateModel(
            name='ProductAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Quantity', 'Quantity')], default='Quantity', max_length=200, null=True)),
                ('status_available', models.BooleanField(default=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='products.company')),
                ('formula_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_formula_available', to='products.productformula')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_name_available', to='products.product')),
            ],
        ),
    ]
